// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeUyDPOkNe1vilKBBJAu-0GHhb0tW6n64',
    appId: '1:829800464034:web:c90eac6c2c90b3042fa1fb',
    messagingSenderId: '829800464034',
    projectId: 'lab3-6e39e',
    authDomain: 'lab3-6e39e.firebaseapp.com',
    storageBucket: 'lab3-6e39e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgLTfRf0ifFRWQIM3pmgbmWNmHWn1jfx8',
    appId: '1:829800464034:android:cb48e23c0d12f9f62fa1fb',
    messagingSenderId: '829800464034',
    projectId: 'lab3-6e39e',
    storageBucket: 'lab3-6e39e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqCcBeBFEm1XI3YwAmH7nUDIBl_LRoaZI',
    appId: '1:829800464034:ios:60cddc53d462bb8c2fa1fb',
    messagingSenderId: '829800464034',
    projectId: 'lab3-6e39e',
    storageBucket: 'lab3-6e39e.appspot.com',
    iosBundleId: 'com.example.lab3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqCcBeBFEm1XI3YwAmH7nUDIBl_LRoaZI',
    appId: '1:829800464034:ios:611752a5fc9ba1542fa1fb',
    messagingSenderId: '829800464034',
    projectId: 'lab3-6e39e',
    storageBucket: 'lab3-6e39e.appspot.com',
    iosBundleId: 'com.example.lab3.RunnerTests',
  );
}
